### ISSUE TITLE
 BZ::Client::User - "Undefined subroutine. error."

### ISSUE THREAD

**Issue by zumaroc** [djzort/BZ-Client#6]
1. Create, a class method returns undefined?

"Undefined subroutine &BZ::Client::User::_create called at.."
![image](https://user-images.githubusercontent.com/76053986/105168717-80845200-5ae8-11eb-8d5b-f18a98304fb1.png)

2. Steps to reproduce:

`my $id    = BZ::Client::User->create( $client, \%params );`

Here's a snapshot of /usr/local/share/perl/5.32.0/BZ/Client/User.pm
![image](https://user-images.githubusercontent.com/76053986/105168578-4fa41d00-5ae8-11eb-9b2c-ee41cf4f3979.png)

Thanks,
Zroc

**Comment by djzort** [comment]
I've just uploaded a new version to cpan.

Please try out v4.4004 and reopen this if its not fixed
