### ISSUE TITLE
Token-IDs are stored in log files. 

### ISSUE THREAD

**Issue by zumaroc** [djzort/BZ-Client#7]
When making BZ:Client login request, token-IDs are stored in log files. When api_key is used for login, issue does not occur. 
This happens when user and password is used for login.

Is there a way to turn this off? 

Now, what works is to add a logger after login is successful.

![image](https://user-images.githubusercontent.com/76053986/110474973-4e39ae80-80ae-11eb-8d82-b57a08aad1e8.png)

**Comment by djzort** [comment]
Are you defining your own logging function via logger() ?

**Comment by zumaroc** [comment]
Yes!

Like so:

```
my $bz_client_logger = sub  { #BZ::Client logger subroutine 
	 my ($level, $msg) = @_;
			        print STDERR "$level $msg\n";
			        return 1;
	
};
```

**Comment by djzort** [comment]
Just filter out the values you dont want?

**Comment by zumaroc** [comment]
Indeed. Thanks!
